name: GLOW
on:
  push:
    branches:
      - main
jobs:
  DOC-DEPLOY:
    name: doc-deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Run build
        uses: ./.github/doc-deploy
        env:
          ACCESS_TOKEN: ${{ secrets.MY_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build
          BUILD_SCRIPT: npm install && npm run build
